### ISSUE TITLE
Traits fails to build on Python 3.13

### ISSUE THREAD

**Issue by ptmcg** [enthought/traits#1811]
From the [Python 3.13 docs](https://docs.python.org/3.13/whatsnew/3.13.html#removed-c-apis):

> Remove the old trashcan macros Py_TRASHCAN_SAFE_BEGIN and Py_TRASHCAN_SAFE_END. Replace both with the new macros Py_TRASHCAN_BEGIN and Py_TRASHCAN_END. (Contributed by Irit Katriel in [gh-105111](https://github.com/python/cpython/issues/105111).)

Traits still uses `Py_TRASHCAN_SAFE_BEGIN/END` macros. When trying to pip install under python 3.13, I get this link failure:

```
     Creating library build\temp.win-amd64-cpython-313\Release\traits\ctraits.cp313-win_amd64.lib and object build\temp.win-amd64-cpython-313\Release\traits\ctraits.cp313-win_amd64.exp
  ctraits.obj : error LNK2001: unresolved external symbol Py_TRASHCAN_SAFE_END
  ctraits.obj : error LNK2001: unresolved external symbol Py_TRASHCAN_SAFE_BEGIN
  build\lib.win-amd64-cpython-313\traits\ctraits.cp313-win_amd64.pyd : fatal error LNK1120: 2 unresolved externals
```

Traits is not installable under Python 3.13.

**Comment by mdickinson** [comment]
Thanks for the report; this was previously reported in #1765, and should be already fixed in the main branch.

(We do still need to make a release at some point, though.)

**Comment by mdickinson** [comment]
@ptmcg Indeed. Unfortunately, a release is also dependent on someone having the time and resources to make that release. It's on the to-do list, but it still might take a while.

**Comment by ptmcg** [comment]
It doesn't really hold me up - I don't use `traits` directly, but I test with it in my `littletable` project for compatibility (can a `littletable.Table` work properly when populated with `traits` objects). For now I'll remove `traits` from my compatibility packages under Python 3.13, and I'll watch for when a new release comes out.
