### ISSUE TITLE
Clone traits does not seem to work with dynamic Enum

### ISSUE THREAD

**Issue by sallenEnth** [enthought/traits#1622]
Noticed that issue on Linux with traits 6.3.2

When my class has a trait which value are set by a dynamic Enum, it is not correctly copied by ``clone_traits``. Here is a small example to reproduce the issue, (it might not be the best example, but I did not want to spend too much time building a fake example). We can talk about the real case where I noticed the issue.

```
from traits.api import Enum, HasStrictTraits, List, Str, Tuple
  

class Company(HasStrictTraits):
    #: List of departments
    departments = List(Str)

    #: Projects: (name, department)
    projects = List(Tuple(Str, Enum(values="departments")))

    def set_departments(self):
       # This is not realistic, it just to demontrate the issue
       self.departments = ["marketing", "training", "consulting"]


def demo():
    company = Company()
    company.set_departments()
    projects = []
    for i, project in enumerate(["hello", "world", "bye"]):
        projects.append((project, company.departments[i]))
    company.projects = projects

    cie = company.clone_traits()
    print(company.projects)
    print(cie.projects)  # This is always empty


if __name__ == "__main__":
    demo()
```

**Comment by sallenEnth** [comment]
I understand that the issue might be difficult to fix. If there will not be a fix I think we should improve the documentation about the ``clone_traits`` method in the Advanced Topics.

**Comment by mdickinson** [comment]
Issue confirmed on the main branch (under Python 3.10). Here's a slightly simplified example (that removes the `Tuple` involvement):

```python
from traits.api import Enum, HasStrictTraits, List, Str


class Company(HasStrictTraits):
    departments = List(Str)

    projects = List(Enum(values="departments"))


def demo():
    company = Company(
        departments=["marketing"],
        projects=["marketing"],
    )

    cie = company.clone_traits()
    print(company.projects)
    print(cie.projects)  # This is always empty


if __name__ == "__main__":
    demo()
```

On my machine, output is:
```python
(traits) mdickinson@mirzakhani traits % python bug.py
['marketing']
[]
```

**Comment by mdickinson** [comment]
Note: this also appears to be a regression in Traits 6.0; in Traits 5.2.0 it works as expected.

**Comment by mdickinson** [comment]
Semi-diagnosis: `copy.deepcopy` is failing on the `company.projects` `TraitListObject`. When running the following code:

```python
import copy
from traits.api import Enum, HasStrictTraits, List, Str

class Company(HasStrictTraits):
    departments = List(Str)
    projects = List(Enum(values="departments"))

company = Company(
    departments=["marketing"],
    projects=["marketing"],
)

copy.deepcopy(company.projects)
```

I get this traceback:
```
(traits) mdickinson@mirzakhani traits % python bug.py   
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/traits/bug.py", line 13, in <module>
    copy.deepcopy(company.projects)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_list_object.py", line 813, in __deepcopy__
    return TraitListObject(
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_list_object.py", line 582, in __init__
    super().__init__(
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_list_object.py", line 213, in __init__
    super().__init__(self.item_validator(item) for item in iterable)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_list_object.py", line 213, in <genexpr>
    super().__init__(self.item_validator(item) for item in iterable)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_list_object.py", line 865, in _item_validator
    return trait_validator(object, self.name, value)
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_types.py", line 2235, in _validate
    if safe_contains(value, xgetattr(object, self.name)):
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_base.py", line 322, in xgetattr
    return getattr(object, names[-1])
AttributeError: 'function' object has no attribute 'departments'
```

**Comment by mdickinson** [comment]
This isn't looking easy to fix. Part of the reason that it worked in 5.2.0 is that we apparently didn't do validation properly in 5.2.0: with the example code, I can append anything I like (e.g., floats instead of strings) to `company.projects` without triggering a validation error. We probably don't want to go back to that state.

Part of the problem is that it's not even clear what doing a deep copy of a `TraitListObject` should do with respect to its link to the `HasTraits` object: should it recursively copy the `HasTraits` object it belongs to, or should it continue to refer to the same `HasTraits` object as before? I guess the former. It's somewhat clearer in the common case where we're starting out with a `HasTraits` object.

**Comment by sallenEnth** [comment]
@mdickinson Thank you for taking a look into it. That was my understanding of the issue. That is why I am thinking that we could look into improving the documentation rather. Currently the ``clone_traits`` method is mentioned in the "Advanced Topics" section but there is no mention of any issue.

Would it make sense to suggest that when a class has such type of traits like ``List(Enum)`` or probably dynamic ``Range`` the user should define its own method to clone an instance if needed? For the example above you could define it like:

```
class Company(HasTraits):
    departments = List(Str)
    projects = List(Enum(values="departments"))

    def clone_traits(self):
        new = super().clone_traits(traits=["departments"])
        new.projects = list(self.projects)
        return new
```
You could also add parameters deep, and others to allow more option.

**Comment by mdickinson** [comment]
#1624 has a quick fix. It doesn't address the deeper issues with cloning, but it gets the original code here working and should represent a net improvement over the current state. The `object=lambda: None` lines in the `__deepcopy__` methods were simply wrong.

**Comment by mdickinson** [comment]
> Would it make sense to suggest that when a class has such type of traits like `List(Enum)` or probably dynamic `Range` the user should define its own method to clone an instance if needed?

I _think_ the fix in #1624 should make this unnecessary. But we should at least document the current state that cloning a trait means potentially losing validation for lists, dicts and sets:
