### PR TITLE
Fix Traits build error on Python 3.13

### LINKED ISSUE #1765: Fails to build with python 3.13
python-Traits fails to build with Python 3.13.0a1.
```
traits/ctraits.c: In function ‘has_traits_dealloc’:
traits/ctraits.c:811:5: error: implicit declaration of function ‘Py_TRASHCAN_SAFE_BEGIN’; did you mean ‘Py_TRASHCAN_BEGIN’? [-Werror=implicit-function-declaration]
  811 |     Py_TRASHCAN_SAFE_BEGIN(obj);
      |     ^~~~~~~~~~~~~~~~~~~~~~
      |     Py_TRASHCAN_BEGIN
traits/ctraits.c:814:5: error: implicit declaration of function ‘Py_TRASHCAN_SAFE_END’; did you mean ‘Py_TRASHCAN_END’? [-Werror=implicit-function-declaration]
  814 |     Py_TRASHCAN_SAFE_END(obj);
      |     ^~~~~~~~~~~~~~~~~~~~
      |     Py_TRASHCAN_END
```
According to https://docs.python.org/3.13/whatsnew/3.13.html:
Remove the old trashcan macros Py_TRASHCAN_SAFE_BEGIN and Py_TRASHCAN_SAFE_END.
They should be replaced by the new macros Py_TRASHCAN_BEGIN and Py_TRASHCAN_END.
The new macros were added in Python 3.8 and the old macros were deprecated in Python 3.11.
(Contributed by Irit Katriel in gh-105111.)

https://docs.python.org/3.13/whatsnew/3.13.html

### PR DESCRIPTION
**Pull request by mdickinson**
This PR updates the core test workflow to run tests on the in-development 3.13 version of Python, and fixes use of the now-removed `Py_TRASHCAN_SAFE_BEGIN/END` macros.

Fixes #1765.

### CODE REVIEW

File: traits/ctraits.c [hunk 1]
```diff
@@ -808,10 +808,18 @@ static void
 has_traits_dealloc(has_traits_object *obj)
 {
     PyObject_GC_UnTrack(obj);
+#if PY_VERSION_HEX < 0x03080000
```
Comment (mdickinson) [inline traits/ctraits.c:811]: We can simplify this if we drop support for Python 3.7, but doing that in this PR would be unnecessarily complicated. I've opened a separate issue #1769.

**Review by corranwebster — APPROVED** [review]
LGTM
